environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

install:
  - ps: Install-Product node 6.6.0 x64
  - git submodule update --init
  - npm install

build_script:
  - npm run vscode:prepublish

test_script:
  - npm test --silent
